export const mockPayments: any[] = [
  {
    id: "pay_001",
    createdAt: "2025-12-10T09:15:00.000Z",
    clientName: "A. Rivera",
    amountCents: 6500,
    tipCents: 1000,
    method: "CARD",
    status: "COMPLETED",
    squarePaymentUrl: "https://squareup.com/dashboard/sales/transactions",
    items: [{ id: "li_1", name: "Service A", qty: 1, unitAmountCents: 6500 }],
    refunds: [],
  },
  {
    id: "pay_002",
    createdAt: "2025-12-10T11:42:00.000Z",
    clientName: "S. Chen",
    amountCents: 9000,
    tipCents: 0,
    method: "CASH",
    status: "COMPLETED",
    squarePaymentUrl: "https://squareup.com/dashboard/sales/transactions",
    items: [{ id: "li_2", name: "Service B", qty: 1, unitAmountCents: 9000 }],
    refunds: [],
  },
  {
    id: "pay_003",
    createdAt: "2025-12-11T13:05:00.000Z",
    clientName: "J. Patel",
    amountCents: 12000,
    tipCents: 1500,
    method: "WALLET",
    status: "COMPLETED",
    squarePaymentUrl: "https://squareup.com/dashboard/sales/transactions",
    items: [{ id: "li_3", name: "Service C", qty: 1, unitAmountCents: 12000 }],
    refunds: [],
  },
  {
    id: "pay_004",
    createdAt: "2025-12-11T15:30:00.000Z",
    clientName: "M. Johnson",
    amountCents: 4500,
    tipCents: 700,
    method: "CARD",
    status: "PENDING",
    squarePaymentUrl: "https://squareup.com/dashboard/sales/transactions",
    items: [{ id: "li_4", name: "Service A", qty: 1, unitAmountCents: 4500 }],
    refunds: [],
  },
  {
    id: "pay_005",
    createdAt: "2025-12-12T10:18:00.000Z",
    clientName: "L. Gomez",
    amountCents: 7800,
    tipCents: 1200,
    method: "CARD",
    status: "COMPLETED",
    squarePaymentUrl: "https://squareup.com/dashboard/sales/transactions",
    items: [{ id: "li_5", name: "Service D", qty: 1, unitAmountCents: 7800 }],
    refunds: [],
  },
  {
    id: "pay_006",
    createdAt: "2025-12-12T14:55:00.000Z",
    clientName: "R. Singh",
    amountCents: 11000,
    tipCents: 0,
    method: "BANK_TRANSFER",
    status: "COMPLETED",
    squarePaymentUrl: "https://squareup.com/dashboard/sales/transactions",
    items: [{ id: "li_6", name: "Service C", qty: 1, unitAmountCents: 11000 }],
    refunds: [],
  },
  {
    id: "pay_007",
    createdAt: "2025-12-13T09:40:00.000Z",
    clientName: "E. Brown",
    amountCents: 5200,
    tipCents: 500,
    method: "CASH",
    status: "COMPLETED",
    squarePaymentUrl: "https://squareup.com/dashboard/sales/transactions",
    items: [{ id: "li_7", name: "Service A", qty: 1, unitAmountCents: 5200 }],
    refunds: [],
  },
  {
    id: "pay_008",
    createdAt: "2025-12-13T16:22:00.000Z",
    clientName: "T. Nguyen",
    amountCents: 13400,
    tipCents: 2000,
    method: "CARD",
    status: "COMPLETED",
    squarePaymentUrl: "https://squareup.com/dashboard/sales/transactions",
    items: [{ id: "li_8", name: "Service E", qty: 1, unitAmountCents: 13400 }],
    refunds: [],
  },
  {
    id: "pay_009",
    createdAt: "2025-12-14T11:07:00.000Z",
    clientName: "C. Walker",
    amountCents: 6000,
    tipCents: 0,
    method: "WALLET",
    status: "FAILED",
    squarePaymentUrl: "https://squareup.com/dashboard/sales/transactions",
    items: [{ id: "li_9", name: "Service B", qty: 1, unitAmountCents: 6000 }],
    refunds: [],
  },
  {
    id: "pay_010",
    createdAt: "2025-12-14T18:45:00.000Z",
    clientName: "D. Kim",
    amountCents: 9800,
    tipCents: 1500,
    method: "CARD",
    status: "COMPLETED",
    squarePaymentUrl: "https://squareup.com/dashboard/sales/transactions",
    items: [{ id: "li_10", name: "Service C", qty: 1, unitAmountCents: 9800 }],
    refunds: [],
  },
  {
    id: "pay_011",
    createdAt: "2025-12-15T10:12:00.000Z",
    clientName: "H. Ali",
    amountCents: 15000,
    tipCents: 2500,
    method: "CARD",
    status: "COMPLETED",
    squarePaymentUrl: "https://squareup.com/dashboard/sales/transactions",
    items: [{ id: "li_11", name: "Service F", qty: 1, unitAmountCents: 15000 }],
    refunds: [],
  },
  {
    id: "pay_012",
    createdAt: "2025-12-15T13:37:00.000Z",
    clientName: "P. Martin",
    amountCents: 7200,
    tipCents: 800,
    method: "CASH",
    status: "COMPLETED",
    squarePaymentUrl: "https://squareup.com/dashboard/sales/transactions",
    items: [{ id: "li_12", name: "Service A", qty: 1, unitAmountCents: 7200 }],
    refunds: [],
  },
  {
    id: "pay_013",
    createdAt: "2025-12-16T09:55:00.000Z",
    clientName: "K. O’Neil",
    amountCents: 8800,
    tipCents: 0,
    method: "BANK_TRANSFER",
    status: "COMPLETED",
    squarePaymentUrl: "https://squareup.com/dashboard/sales/transactions",
    items: [{ id: "li_13", name: "Service D", qty: 1, unitAmountCents: 8800 }],
    refunds: [],
  },
  {
    id: "pay_014",
    createdAt: "2025-12-16T17:20:00.000Z",
    clientName: "N. Brooks",
    amountCents: 4300,
    tipCents: 500,
    method: "WALLET",
    status: "PENDING",
    squarePaymentUrl: "https://squareup.com/dashboard/sales/transactions",
    items: [{ id: "li_14", name: "Service A", qty: 1, unitAmountCents: 4300 }],
    refunds: [],
  },
  {
    id: "pay_015",
    createdAt: "2025-12-17T12:00:00.000Z",
    clientName: "F. Rossi",
    amountCents: 10200,
    tipCents: 1800,
    method: "CARD",
    status: "COMPLETED",
    squarePaymentUrl: "https://squareup.com/dashboard/sales/transactions",
    items: [{ id: "li_15", name: "Service E", qty: 1, unitAmountCents: 10200 }],
    refunds: [],
  },
  {
    id: "pay_016",
    createdAt: "2025-12-18T10:10:00.000Z",
    clientName: "I. Petrov",
    amountCents: 12500,
    tipCents: 0,
    method: "CARD",
    status: "REFUNDED",
    squarePaymentUrl: "https://squareup.com/dashboard/sales/transactions",
    items: [{ id: "li_16", name: "Service C", qty: 1, unitAmountCents: 12500 }],
    refunds: [
      {
        id: "ref_001",
        createdAt: "2025-12-19T09:00:00.000Z",
        amountCents: 12500,
        reason: "Customer cancellation",
        status: "COMPLETED",
      },
    ],
  },
  {
    id: "pay_017",
    createdAt: "2025-12-19T14:30:00.000Z",
    clientName: "B. Edwards",
    amountCents: 5600,
    tipCents: 600,
    method: "CASH",
    status: "COMPLETED",
    squarePaymentUrl: "https://squareup.com/dashboard/sales/transactions",
    items: [{ id: "li_17", name: "Service B", qty: 1, unitAmountCents: 5600 }],
    refunds: [],
  },
  {
    id: "pay_018",
    createdAt: "2025-12-20T09:05:00.000Z",
    clientName: "Y. Tanaka",
    amountCents: 14000,
    tipCents: 2200,
    method: "CARD",
    status: "COMPLETED",
    squarePaymentUrl: "https://squareup.com/dashboard/sales/transactions",
    items: [{ id: "li_18", name: "Service F", qty: 1, unitAmountCents: 14000 }],
    refunds: [],
  },
  {
    id: "pay_019",
    createdAt: "2025-12-20T16:48:00.000Z",
    clientName: "G. Wilson",
    amountCents: 6100,
    tipCents: 0,
    method: "WALLET",
    status: "FAILED",
    squarePaymentUrl: "https://squareup.com/dashboard/sales/transactions",
    items: [{ id: "li_19", name: "Service A", qty: 1, unitAmountCents: 6100 }],
    refunds: [],
  },
  {
    id: "pay_020",
    createdAt: "2025-12-21T18:32:00.000Z",
    clientName: "Z. Ahmed",
    amountCents: 11800,
    tipCents: 1700,
    method: "CARD",
    status: "COMPLETED",
    squarePaymentUrl: "https://squareup.com/dashboard/sales/transactions",
    items: [{ id: "li_20", name: "Service D", qty: 1, unitAmountCents: 11800 }],
    refunds: [],
  },
];
